### ISSUE TITLE
Is there a plan to use an identifier for repository?

### ISSUE THREAD

**Issue by mariapraetzellis** [RDA-DMP-Common/RDA-DMP-Common-Standard#11]
DMPRoadmap is working towards implementing the Common Standard. In mapping out the fields between our systems and the common standard, I was wondering how we should best identify the repository where a dataset is hosted.  I was considering using re3data.org for their a registry of research data repositories. For example: http://doi.org/10.17616/R3K64N. 
I didn't see mention of how/where to define the repository in the Common Standard.

**Comment by peterneish** [comment]
I think this makes sense and would improve the model for this use case.

**Comment by TomMiksa** [comment]
We have added host_id to the model specification. It is already depicted in the diagrams. Our documentation will be refreshed soon (@paulwalk)
