### ISSUE TITLE
typos in the documentation

### ISSUE THREAD

**Issue by Zack-83** [RDA-DMP-Common/RDA-DMP-Common-Standard#12]

**Comment by Zack-83** [comment]
The **description** of the field `grant_id` was set equal to `#REF!` (heritage from Excel)
`resource` was reproduced as `reosurce`.
Does it make sens to give the same name to fields hierarchically ordered under each other? The upper `contact_id` is a structure, while the lower `contact_id` is a string...

**Comment by paulwalk** [comment]
@Zack-83 Many thanks for this useful feedback! We agree with your comments about the unnecessary extra `contact_id` structure and have flattened this (and done the same for the similar arrangements in other properties which use the `id` and `id_type` patterns.

I have also removed the `#REF!` from the `grant_id` property.

**Comment by Zack-83** [comment]
Thanks for the fast reaction. Please don't forget to change `reosurce` back into `resource` !

**Comment by Zack-83** [comment]
Thanks for reacting. Please don't forget to change reosurce back into 
resource !

Regards,

Giacomo



Von:    "Paul Walk" <notifications@github.com>
An:     "RDA-DMP-Common/RDA-DMP-Common-Standard" 
<RDA-DMP-Common-Standard@noreply.github.com>
Kopie:  "Zack-83" <giacomo.lanza@ptb.de>, "Mention" 
<mention@noreply.github.com>
Datum:  08.10.2019 11:53
Betreff:        Re: [RDA-DMP-Common/RDA-DMP-Common-Standard] typos in the 
documentation (#12)



@Zack-83 Many thanks for this useful feedback! We agree with your comments 
about the unnecessary extra contact_id structure and have flattened this 
(and done the same for the similar arrangements in other properties which 
use the id and id_type patterns.
I have also removed the #REF! from the grant_id property.
?
