### ISSUE TITLE
Explain URLs better

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/RDA-DMP-Common-Standard#13]
Please explain for a data set distribution what is the difference between a "download" and an "access" URL

**Comment by TomMiksa** [comment]
Thanks, we will update the documentation. 

Both of them are described by the W3C DCAT:

"A URL of the resource that gives access to a distribution of the dataset. e.g. landing page."
https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_access_url 

"The URL of the downloadable file in a given format. E.g. CSV file or RDF file."
https://www.w3.org/TR/vocab-dcat-2/#Property:distribution_download_url

Access_url is basically the ladning page and the download_url is the direct link to the file.

**Comment by paulwalk** [comment]
I have updated the documentation sources to include these descriptions (will commit these changes later today). Closing this issue.
