### ISSUE TITLE
Distribution contains a title, the dataset does not

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/RDA-DMP-Common-Standard#15]
I expected to have a title for a data set, each distribution is equivalent and should use the same title? In the current model, the distribution has a "title", the dataset has a "description". 

If a distribution can contain a subset of a dataset, I am misunderstanding the model and the documentation may need to be augmented.

**Comment by TomMiksa** [comment]
For the compliance with the W3C DCAT specification we have title and description in both Dataset and the Distribution. I agree that in some cases these might be identical, but in most cases the Dataset represents a more abstract concept, while the distribution can point to a specific file.

https://www.w3.org/TR/vocab-dcat-2/#Class:Dataset
https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution

We may need to provide more examples.

**Comment by paulwalk** [comment]
I have added the following to the descriptions of `dataset/title` and `distribution/title`:

> Title is a property in both Dataset and Distribution, in compliance with W3C DCAT. In some cases these might be identical, but in most cases the Dataset represents a more abstract concept, while the distribution can point to a specific file.

I have added the following to the descriptions of `dataset/description` and `distribution/description `:

> Description is a property in both Dataset and Distribution, in compliance with W3C DCAT. In some cases these might be identical, but in most cases the Dataset represents a more abstract concept, while the distribution can point to a specific file.

I will commit these changes later today. I am closing this issue now.
