### ISSUE TITLE
Some contributors may have more than one role

### ISSUE THREAD

**Issue by rwwh** [RDA-DMP-Common/RDA-DMP-Common-Standard#18]
Some people associated to a project may fulfill multiple roles, but the model has "exactly one" here. Repeating a person should not be necessary.

**Comment by TomMiksa** [comment]
Currently a person must be listed several times.
Rob is a Reseacher
Rob is a Manager
Instead of
Rob is a {Manager, Researcher}.
The model is not limiting you in this sense. 

We can also make a change:
Contributor/role -> Cardinality set to 1..* so that one person could have multiple roles

**Comment by paulwalk** [comment]
I think we should change the cardinality of Contributor/role to [1..n]. Since Tomasz has already suggested this too, and I cannot see any potential negative effect, I will make this change in the specification and close this issue now.
