### ISSUE TITLE
cannot load dmp.genomics.unit.1.0.0.owl 

### ISSUE THREAD

**Issue by froggypaule** [RDA-DMP-Common/RDA-DMP-Common-Standard#24]
Dear all,
As you see I cannot load the ontology using protégé. Now I am a  total newbie and am likely to do most of this the wrong way. Maybe this is not the place to ask help here, but I try anyway.

"
 [Fatal Error] :45:94: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.
Failed to load imported ontology at https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/ontologies/extensions/dcso.extension.2019.10.19.1.0.0.owl 
"

I am Paulette Lieby, from IFB (Institut Francąis de Bioinformatique) and I am very interested by the work presented in the poster     An ontology for the DMP Common Standard Model.

many thanks, 
Regards,
Paulette.

**Comment by TomMiksa** [comment]
Hi,
@JoaoMFCardoso is maintining the ontology. I hope he can asnwer your question.

To my best knwoledge, the ontology is not updated to be compliant with the current revision of the standard. There are some minimal discepancies in the field names, cardinalities, etc.

Tomasz

**Comment by froggypaule** [comment]
Hello Tomasz,
Thanks for that. Compliance with the standard doesn't matter : I am looking into means of (easily) translating the ANR (Agence Nationale de la Recherche) DMP template (parts of) into an ontologie. And Joao's work is among the very few working in this space. 
Paulette.
