### ISSUE TITLE
TechnicalResources, metadata, and Security

### ISSUE THREAD

**Issue by NZR** [RDA-DMP-Common/RDA-DMP-Common-Standard#3]
Consider the following instance of the model. 

DMP1 --> TechnicalResource: Telescope
|
DataSet1 --> TechnicalResource: Microscope

The existence of the 2 relationships from the DMP and from the DataSet to TechnicalResources can lead to inconsistencies in the instances. 
In the example above, there is no clear way to determine which information is correct or suitable for the DMP/Dataset.

**Comment by TomMiksa** [comment]
We have updated the model to have just one connection: Dataset -> TechnicalResource.
As a result DMP must have at least 1 Dataset. Such a dataset can be minimal and tools processing a dmp, do not have to present it to the user.
