### ISSUE TITLE
Number of funding per project inconsistency

### ISSUE THREAD

**Issue by MarekSuchanek** [RDA-DMP-Common/RDA-DMP-Common-Standard#31]
- Diagram says that project has 0..* funding
- In JSON schema there as array without limitation, so 0..* as well
- But [table in README](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#properties-in-project) states 0..1

**Comment by hmpf** [comment]
I think this is the same as #42, which has a PR: #41.
