### ISSUE TITLE
Optional lists with mandatory items (license, security_and_privacy)

### ISSUE THREAD

**Issue by MarekSuchanek** [RDA-DMP-Common/RDA-DMP-Common-Standard#32]
There are cases where a list must contain at least one item but at the same time the list is optional in the parent object, so the limitation does not make much sense:

- https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/examples/JSON/JSON-schema/1.0/maDMP-schema-1.0.json#L499 (actually in [README](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#properties-in-distribution) is 0..n - so maybe just a "bug" in the schema)
- https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/examples/JSON/JSON-schema/1.0/maDMP-schema-1.0.json#L678 (same, again 0..n in [https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard#properties-in-dataset])

**Comment by TomMiksa** [comment]
@SotosTsepe can you please check this and update the JSON schema if necessary

**Comment by SotosTsepe** [comment]
@MarekSuchanek Thanks for your feedback! Putting the property `minItems` set to 1 ensures that an empty array is not given, because it doesn't make sense. This property doesn't affect the cardinality of `license` for example; one can still omit `license` and the JSON will pass validation, but were he to specify it, the array would have to have at least one object contained.

**Comment by MarekSuchanek** [comment]
OK, so if there is no license, it should be omitted ("we don't care about licensing at all"). Implementation-wise it is more complicated when compared to allowing empty array (which means "there is no license"). One must have extra checks to leave it out when list of licenses is empty during importing and have default for non-present list when exporting. But if it has some strong meaning in the schema, why not...

Nevertheless, it would be good to explain it briefly in the description as I think this may cause issues to others as well.

**Comment by TomMiksa** [comment]
We eventually decided not to put any constraints on the specific serialization. In this case JSON specification. This means that both empty arrays, as well as simply omitting a field is permitted. There is a new version of JSON schema (1.1) that permits that.

**Comment by MarekSuchanek** [comment]
OK, great... I will revisit the template for DSW and update it according to the new version.

(Will be there also a git tag for reference?)

**Comment by TomMiksa** [comment]
Yes, it will be 1.1- later today.
