### ISSUE TITLE
Funding cardinality mismatch

### ISSUE THREAD

**Issue by jochenklar** [RDA-DMP-Common/RDA-DMP-Common-Standard#42]
Funding has 0..n cardinality in the diagram, but 0..1 in README.md. I created a PR https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/pull/41.

**Comment by hmpf** [comment]
The correct cardinalities should also be in the "Structure" list so you can see at a glance what is repeatable or not. (I hope the Structure-list is autogenerated!)

**Comment by hmpf** [comment]
Previous issue on the same matter: #31
