### ISSUE TITLE
Project dates should be optional

### ISSUE THREAD

**Issue by mariapraetzellis** [RDA-DMP-Common/RDA-DMP-Common-Standard#49]
We've run into an issue when trying to conform to the Common Standard for DMPs because many of our users do not have project dates upon the creation of a DMP within the tool. Exact project dates are sometimes not know upon DMP creation and are often determined by the funder upon award. We would like to request that projectStart and projectEnd fields be optional so that users can fill in an accurate date when it is known.

**Comment by TomMiksa** [comment]
I think we can do that.
