### ISSUE TITLE
Terminology change

### ISSUE THREAD

**Issue by briri** [RDA-DMP-Common/RDA-DMP-Common-Standard#57]
In the [FAQ](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/docs/FAQ.md#what-is-a-difference-between-dataset-and-a-distribution) here we state that:
"Dataset can be understood as a logical entity depicting data, e.g. raw data, software, publication, etc. Distribution points to a specific instance of a dataset. Hence, distribution contains information like format and size of files."

Should we consider switching to use the term 'research_output', 'output' , or something similar instead of 'dataset' to make it more generic? 
From:
```js
"dataset": [ { "type": "dataset", "title": "My Dataset" }, { "type": "software", "title": "My Software" } ]
```
To:
```js
"research_output": [ { "type": "dataset", "title": "My Dataset" }, { "type": "software", "title": "My Software" } ]
```

**Comment by TomMiksa** [comment]
We would break the compliance with the [W3C DCAT](https://www.w3.org/TR/vocab-dcat-2/) specification, so I am not sure whether this is the right way to go.

**Comment by briri** [comment]
I see. Ok, will close this out then.
