### ISSUE TITLE
Definition of time and dates to be refined

### ISSUE THREAD

**Issue by cmzwolf** [RDA-DMP-Common/RDA-DMP-Common-Standard#6]
The format used for the date should be specified (e.g. AAAA/MM/DD of the Gregorian Calendar).

Moreover the time used (ex. in the fields "created" and "modified") miss the time zone used for expressing the time.

**Comment by dcmi** [comment]
I suggest we standardise on ISO 8601 for dates - e.g. today's date would be expressed as:

`2019-04-17`

**Comment by TomMiksa** [comment]
Current specification of the application profile has no information on which date/time standard to use.

**Comment by hmpf** [comment]
For the time bit in datetimes, the most explicit storage/interchange format is hh:mm:ssZ, that is: 24 hours, 60 minutes, up to 62 seconds (because leap seconds), and timezone set to UTC as a Z.

**Comment by hmpf** [comment]
Here's ECMA itself weighing in: 

[Ecma-262 Edition 5.1: 15.9.1.15 Date Time String Format](https://ecma-international.org/ecma-262/5.1/#sec-15.9.1.15

**YYYY-MM-DDTHH:mm:ss.sssZ** where **Z** is either a `Z` or  `+HH:mm`.

**Comment by TomMiksa** [comment]
We will use ISO 8601, because it is a W3C organisation and is also used by the DCAT specification that we hevily rely on.
