### ISSUE TITLE
Are there any plans to use real data to provide examples?

### ISSUE THREAD

**Issue by rowlandm** [RDA-DMP-Common/RDA-DMP-Common-Standard#9]
eg. in https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/tree/master/examples/JSON

It was nice to see dummy examples, but it would be nice to see how this standard handles real complex data. 

Maybe it would be useful to talk to someone like Bioplatforms Australia to see how their datasets would map to this schema.  They have been doing some complicated multi-omics datasets for stem cells and sepsis recently.

Sorry - I just saw the user stories repo, but still think some complicated examples that could then inform the user stories would be really useful.

**Comment by rowlandm** [comment]
Bonus question,  how do you handle multiple institutions/ organizations? The only thing I can see is DMstaff.

eg. industry and cross institution datasets like HILDA from Melbourne Institute

**Comment by TomMiksa** [comment]
The assumption of the standard is not to copy information provided somewhere else into the maDMP, if it can queried from somewhere else. The standard is also independent of the domain for which the maDMP is created. This means, that all complex types of data are "only" Datasets and Distributions to us. The standard provides a common set of fields, like identifier, format, download_url, etc. It makes no difference if they refer to bioinformatics data or raw data from satellites. 
In the presentation, there are links to some prototype tools, you can find there human-readable DMPs that were converted into machine-actionable. In future, we plan to publish some more examples.

Ad. bonus questions: We have defined the Security and Privacy object in which such additional information on security requirements can be provided. You can see it as an extension point (abstract class if we speak programming language). For now, one can query the Security and Privacy object to find out whether there are any specific constraints (title and description fields). We believe that modelling different security an privacy requirements was beyond the scope of this WG. However, in case there is a demand for that, it is possible to incorporate an extension.

**Comment by rowlandm** [comment]
Thanks!
